name: release
on: [push, pull_request]
jobs:
  windows:
    name: windows
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - name: Install Depencies
      run: |
         msys2 -c 'pacman -S --noconfirm libxslt base-devel mingw-w64-x86_64-clang'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2  
    - name: Build Generic64
      shell: msys2 {0}
      run: | 
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so
    - name: Build SSSE3
      shell: msys2 {0}
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2
      shell: msys2 {0}
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      shell: msys2 {0}
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so
    - name: Change Artifact Name
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/XKCP-AVX2.dll
          mv bin/AVX512/libXKCP.so bin/artifacts/XKCP-AVX512.dll
          mv bin/SSSE3/libXKCP.so bin/artifacts/XKCP-SSSE3.dll
          mv bin/generic64/libXKCP.so bin/artifacts/XKCP.dll
          mv bin/generic64/libXKCP.so.headers bin/artifacts/libXKCP-win.so.headers
          ls bin/artifacts

    - name: Upload win Artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-win
        path: |
          bin/artifacts/*.dll
          bin/artifacts/libXKCP-win.so.headers          
  linux:
    name: linux
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xsltproc
      run: |
        sudo apt-get update && sudo apt-get install xsltproc -y

    - name: Build Generic64
      run: |
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so

    - name: Build SSSE3
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2 
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so
    - name: Change Artifact Name
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/libXKCP-AVX2.so
          mv bin/AVX512/libXKCP.so bin/artifacts/libXKCP-AVX512.so
          mv bin/SSSE3/libXKCP.so bin/artifacts/libXKCP-SSSE3.so
          mv bin/generic64/libXKCP.so bin/artifacts/libXKCP.so
          mv bin/generic64/libXKCP.so.headers bin/artifacts/libXKCP-linux.so.headers
          ls bin/artifacts
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-linux
        path: |
          bin/artifacts/*.so
          bin/artifacts/libXKCP-linux.so.headers
  osx:
    name: osx
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xsltproc
      run: |
        brew install libxslt
    - name: Build Generic64
      run: |
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so
    - name: Build SSSE3
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2 
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so

    - name: Change Artifact Name
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/libXKCP-AVX2.dylib
          mv bin/AVX512/libXKCP.so bin/artifacts/libXKCP-AVX512.dylib
          mv bin/SSSE3/libXKCP.so bin/artifacts/libXKCP-SSSE3.dylib
          mv bin/generic64/libXKCP.so bin/artifacts/libXKCP.dylib
          mv bin/generic64/libXKCP.so.headers bin/artifacts/libXKCP-osx.so.headers
          ls bin/artifacts
    - name: Upload osx Artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-osx
        path: |
          bin/artifacts/*.dylib
          bin/artifacts/libXKCP-osx.so.headers
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux,osx,windows]
    steps:
      - name: Download XKCP linux
        uses: actions/download-artifact@v2
        with:
          name: XKCP-linux
          path: linux

      - name: Download XKCP osx
        uses: actions/download-artifact@v2
        with:
          name: XKCP-osx
          path: osx

      - name: Download XKCP windows
        uses: actions/download-artifact@v2
        with:
          name: XKCP-win
          path: win                  

      - name: Zip file
        run: |
          mkdir artifacts/
          tar czf artifacts/XKCP-linux.tar.gz -C linux/ $(find linux -type f -name "*.so" -exec basename {} \;) libXKCP-linux.so.headers/
          tar czf artifacts/XKCP-osx.tar.gz -C osx/ $(find osx -type f -name "*.dylib" -exec basename {} \;) libXKCP-osx.so.headers/
          tar czf artifacts/XKCP-win.tar.gz -C win/ $(find win -type f -name "*.dll" -exec basename {} \;) libXKCP-win.so.headers/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: XKCP
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: get_version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Send PR
        run: |
          curl --request POST --url 'https://api.github.com/repos/StirlingLabs/XKCP.NET/dispatches' --header 'authorization: token ${{ secrets.DAEMON_HOOKS  }}' --data '{"event_type": "New XKCP Release", "client_payload": {"tag":"${{ env.RELEASE_VERSION }}"}}' --header "Accept: application/vnd.github.v3+json"
