name: Release
on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  integration:
    name: Integration
    uses: ./.github/workflows/integrate.yml
  
  create-release:
    name: Create Release
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from Integration
        uses: actions/download-artifact@v3
      - name: Repackage as release artifacts
        run: |
          mkdir artifacts/
          tar czf artifacts/XKCP-linux.tar.gz -C XKCP-linux/ $(find XKCP-linux -type f -name "*.so" -exec basename {} \;)
          tar czf artifacts/XKCP-osx.tar.gz -C XKCP-osx/ $(find XKCP-osx -type f -name "*.dylib" -exec basename {} \;)
          tar czf artifacts/XKCP-win.tar.gz -C XKCP-win/ $(find XKCP-win -type f -name "*.dll" -exec basename {} \;)
          tar czf artifacts/XKCP-headers.tar.gz -C XKCP-linux/ include/
      - name: Create release on GitHub
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: XKCP
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Get version from tag ref
        id: version
        run: echo "::set-output name=tag=${GITHUB_REF#refs/*/}"
      - name: Dispatch New XKCP Release event to XKCP.NET
        run: >
          curl -X POST https://api.github.com/repos/StirlingLabs/XKCP.NET/dispatches
          -H 'Authorization: token ${{secrets.DAEMON_HOOKS}}'
          -H "Accept: application/vnd.github.v3+json"
          --data '{"event_type":"New XKCP Release","client_payload":{"tag":"${{steps.version.outputs.tag}}"}}'
