name: Create Release
on:
  push:
    tags:
      - v*
jobs:
  build-win:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - name: Install dependencies
      run: |
         msys2 -c 'pacman -S --noconfirm libxslt base-devel'
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build Generic64
      shell: msys2 {0}
      run: |
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so
    - name: Build SSSE3
      shell: msys2 {0}
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2
      shell: msys2 {0}
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      shell: msys2 {0}
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so
    - name: Rename artifacts
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/XKCP-AVX2.dll
          mv bin/AVX512/libXKCP.so bin/artifacts/XKCP-AVX512.dll
          mv bin/SSSE3/libXKCP.so bin/artifacts/XKCP-SSSE3.dll
          mv bin/generic64/libXKCP.so bin/artifacts/XKCP.dll
          mv bin/generic64/libXKCP.so.headers bin/artifacts/include
          ls bin/artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-win
        path: |
          bin/artifacts/*.dll
          bin/artifacts/libXKCP-win.so.headers
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install xsltproc -y

    - name: Build Generic64
      run: |
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so

    - name: Build SSSE3
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so
    - name: Rename artifacts
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/libXKCP-AVX2.so
          mv bin/AVX512/libXKCP.so bin/artifacts/libXKCP-AVX512.so
          mv bin/SSSE3/libXKCP.so bin/artifacts/libXKCP-SSSE3.so
          mv bin/generic64/libXKCP.so bin/artifacts/libXKCP.so
          mv bin/generic64/libXKCP.so.headers bin/artifacts/include
          ls bin/artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-linux
        path: |
          bin/artifacts/*.so
          bin/artifacts/libXKCP-linux.so.headers
  build-osx:
    name: Build for Mac OSX
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install libxslt
    - name: Build Generic64
      run: |
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so
    - name: Build SSSE3
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so

    - name: Rename artifacts
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/libXKCP-AVX2.dylib
          mv bin/AVX512/libXKCP.so bin/artifacts/libXKCP-AVX512.dylib
          mv bin/SSSE3/libXKCP.so bin/artifacts/libXKCP-SSSE3.dylib
          mv bin/generic64/libXKCP.so bin/artifacts/libXKCP.dylib
          mv bin/generic64/libXKCP.so.headers bin/artifacts/include
          ls bin/artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-osx
        path: |
          bin/artifacts/*.dylib
          bin/artifacts/libXKCP-osx.so.headers
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux,build-osx,build-win]
    steps:
      - name: Download all XKCP artifacts
        uses: actions/download-artifact@v2
      - name: Repackage as release artifacts
        run: |
          mkdir artifacts/
          tar czf artifacts/XKCP-linux.tar.gz -C XKCP-linux/ $(find XKCP-linux -type f -name "*.so" -exec basename {} \;)
          tar czf artifacts/XKCP-osx.tar.gz -C XKCP-osx/ $(find XKCP-osx -type f -name "*.dylib" -exec basename {} \;)
          tar czf artifacts/XKCP-win.tar.gz -C XKCP-win/ $(find XKCP-win -type f -name "*.dll" -exec basename {} \;)
          tar czf artifacts/XKCP-headers.tar.gz -C XKCP-linux/ XKCP-linux/include/
      - name: Create release on GitHub
        uses: softprops/action-gh-release@v0.1.12
        with:
          name: XKCP
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Get version from tag ref
        id: version
        run: echo "::set-output name=tag=${GITHUB_REF#refs/*/}"
      - name: Dispatch New XKCP Release event to XKCP.NET
        run: >
          curl -X POST https://api.github.com/repos/StirlingLabs/XKCP.NET/dispatches
          -H 'Authorization: token ${{secrets.DAEMON_HOOKS}}'
          -H "Accept: application/vnd.github.v3+json"
          --data '{"event_type":"New XKCP Release","client_payload":{"tag":"${{steps.version.outputs.tag}}"}}'
