name: Create Release
on:
  push:
    tags:
      - v*
jobs:
  skip_check:
    name: Skip Run Check
    continue-on-error: true
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.collate_checks.outputs.should_skip }}
    steps:
    -   name: Print Release
        id: force_ci_check
        run: |
            echo $release
        env:
          release: ${{ fromJson(github.event.release) }}
    -   name: Collate Checks
        id: collate_checks
        run: |
          echo "::set-output name=should_skip::false"

  build-win:
    runs-on: windows-2022
    name: Build for Windows
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Add Path Msys64 Directory
      run: |
        echo "c:\msys64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Install msys2 dependencies
      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
      run: |
        pacman -S --noconfirm ucrt64/mingw-w64-ucrt-x86_64-libxslt ucrt64/mingw-w64-ucrt-x86_64-make ucrt64/mingw-w64-ucrt-x86_64-gcc
        ln -s /ucrt64/bin/mingw32-make.exe /ucrt64/bin/make.exe
        echo GCC: $(which gcc)
        echo MAKE: $(which make)
        echo MSYSTEM: ${MSYSTEM}
    - name: Build Generic64
      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
      run: |
        make generic64/libXKCP.so
      env:
        CFLAGS: -O3 -g0 -march=x86-64 -mtune=native
        ASMFLAGS: -march=x86-64 -mtune=native
    - name: Build SSSE3
      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
      run: |
        make SSSE3/libXKCP.so
      env:
        CFLAGS: -O3 -g0 -march=core2 -msse2 -mssse3 -mtune=native
        ASMFLAGS: -march=core2 -mtune=native
    - name: Build AVX2
      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
      run: |
        make AVX2/libXKCP.so
      env:
        CFLAGS: -O3 -g0 -march=skylake -mtune=native
        ASMFLAGS: -march=skylake -mtune=native
    - name: Build AVX512
      shell: msys2_shell.cmd -defterm -no-start -here -ucrt64 {0}
      run: |
        make AVX512/libXKCP.so
      env:
        CFLAGS: -O3 -g0 -march=skylake-avx512 -mtune=native
        ASMFLAGS: -march=skylake-avx512 -mtune=native

    - name: Rename artifacts
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/XKCP-AVX2.dll
          mv bin/AVX512/libXKCP.so bin/artifacts/XKCP-AVX512.dll
          mv bin/SSSE3/libXKCP.so bin/artifacts/XKCP-SSSE3.dll
          mv bin/generic64/libXKCP.so bin/artifacts/XKCP.dll
          mv bin/generic64/libXKCP.so.headers bin/artifacts/include
          ls bin/artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-win
        path: |
          bin/artifacts/*.dll
          bin/artifacts/libXKCP-win.so.headers

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install xsltproc -y

    - name: Build Generic64
      run: |
        CFLAGS="-O3 -g0 -march=x86-64 -mtune=native" ASMFLAGS="-march=x86-64 -mtune=native" make generic64/libXKCP.so
    - name: Build SSSE3
      run: |
        CFLAGS="-O3 -g0 -march=core2 -msse2 -mssse3 -mtune=native" ASMFLAGS="-march=core2 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so
    - name: Rename artifacts
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/libXKCP-AVX2.so
          mv bin/AVX512/libXKCP.so bin/artifacts/libXKCP-AVX512.so
          mv bin/SSSE3/libXKCP.so bin/artifacts/libXKCP-SSSE3.so
          mv bin/generic64/libXKCP.so bin/artifacts/libXKCP.so
          mv bin/generic64/libXKCP.so.headers bin/artifacts/include
          ls bin/artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-linux
        path: |
          bin/artifacts/*.so
          bin/artifacts/include

  build-osx:
    name: Build for Mac OSX
    runs-on: macos-latest
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        brew install libxslt
    - name: Build for ARMv8A (M-series)
      run: |
        CFLAGS="-target aarch64-apple-darwin -arch arm64 -O3 -g0 -march=armv8-a" ASMFLAGS="-march=armv8-a" make ARMv8A/libXKCP.dylib
    - name: Build Generic x86_64
      run: |
        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=x86-64 -mtune=native" ASMFLAGS="-march=x86-64 -mtune=native" make generic64/libXKCP.dylib
    - name: Build SSSE3
      run: |
        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=core2 -msse2 -mssse3 -mtune=native" ASMFLAGS="-march=core2 -mtune=native" make SSSE3/libXKCP.dylib
    - name: Build AVX2
      run: |
        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.dylib
    - name: Build AVX512
      run: |
        CFLAGS="-target x86_64-apple-darwin -arch x86_64 -O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.dylib
    - name: Rename and merge Generic64 and ARMv8A artifacts
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.dylib bin/artifacts/libXKCP-AVX2.dylib
          mv bin/AVX512/libXKCP.dylib bin/artifacts/libXKCP-AVX512.dylib
          mv bin/SSSE3/libXKCP.dylib bin/artifacts/libXKCP-SSSE3.dylib
          lipo bin/generic64/libXKCP.dylib bin/ARMv8A/libXKCP.dylib -create -output bin/artifacts/libXKCP.dylib
          mv bin/generic64/libXKCP.dylib.headers bin/artifacts/include
          ls bin/artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-osx
        path: |
          bin/artifacts/*.dylib
          bin/artifacts/libXKCP-osx.dylib.headers

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux,build-osx,build-win]
    steps:
      - name: Download all XKCP artifacts
        uses: actions/download-artifact@v2
      - name: Repackage as release artifacts
        run: |
          mkdir artifacts/
          tar czf artifacts/XKCP-linux.tar.gz -C XKCP-linux/ $(find XKCP-linux -type f -name "*.so" -exec basename {} \;)
          tar czf artifacts/XKCP-osx.tar.gz -C XKCP-osx/ $(find XKCP-osx -type f -name "*.dylib" -exec basename {} \;)
          tar czf artifacts/XKCP-win.tar.gz -C XKCP-win/ $(find XKCP-win -type f -name "*.dll" -exec basename {} \;)
          tar czf artifacts/XKCP-headers.tar.gz -C XKCP-linux/ XKCP-linux/include/
      - name: Create release on GitHub
        uses: softprops/action-gh-release@v0.1.12
        with:
          name: XKCP
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Get version from tag ref
        id: version
        run: echo "::set-output name=tag=${GITHUB_REF#refs/*/}"
      - name: Dispatch New XKCP Release event to XKCP.NET
        run: >
          curl -X POST https://api.github.com/repos/StirlingLabs/XKCP.NET/dispatches
          -H 'Authorization: token ${{secrets.DAEMON_HOOKS}}'
          -H "Accept: application/vnd.github.v3+json"
          --data '{"event_type":"New XKCP Release","client_payload":{"tag":"${{steps.version.outputs.tag}}"}}'
